# Include macros, variables, and rules
include ../monorepo/make/common.mk
include ../monorepo/make/go.mk  # test, test-short, test-coverage, clean-test, run, build, build-all, clean-build

# Variables required by inclusions
name := command-line-app
main_pkg := ./cmd/command-line-app
