version: "3.8"

volumes:
  redis_data: {}

services:
  # https://hub.docker.com/_/redis
  redis:
    image: redis:7.0.1-alpine
    hostname: redis
    container_name: redis
    restart: always
    volumes:
      - "redis_data:/data"
    ports:
      - "6379:6379"

  service:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: grpc-service
    container_name: grpc-service
    depends_on:
      - redis
    ports:
      - "8080:8080"
      - "9090:9090"
    environment:
      - PROVIDER=Docker
      - REDIS_ADDRESS=redis:6379

  unit-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    hostname: unit-test
    container_name: unit-test
    command: [ "go", "test", "-race", "./..." ]
